#include "ThirdPartyDialog.h"
#include "ui_ThirdPartyDialog.h"

ThirdPartyDialog::ThirdPartyDialog(QWidget* parent)
    : QDialog(parent)
    , mUi(new Ui_ThirdPartyDialog)
{
    mUi->setupUi(this);
    mUi->textView->setHtml(QStringLiteral(
        "<html><body>"

        "<p><b>AudioFile</b><br>"
        "Copyright &copy; 1998&#8209;2000, 2003&#8209;2004, 2010&#8209;2013 Michael Pruett<br>"
        "Copyright &copy; 2000&#8209;2001 Silicon Graphics, Inc.<br>"
        "<br>"
        "This library is free software; you can redistribute it and/or "
        "modify it under the terms of the GNU Lesser General Public "
        "License as published by the Free Software Foundation; either "
        "version 2.1 of the License, or (at your option) any later version.<br>"
        "<br>"
        "This library is distributed in the hope that it will be useful, "
        "but WITHOUT ANY WARRANTY; without even the implied warranty of "
        "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU "
        "Lesser General Public License for more details.<br>"
        "<br>"
        "You should have received a copy of the GNU Lesser General Public "
        "License along with this library; if not, write to the "
        "Free Software Foundation,&nbsp;Inc., 51&nbsp;Franklin Street, Fifth Floor, "
        "Boston, MA&nbsp;&nbsp;02110&nbsp;&#8209;&nbsp;1301&nbsp;&nbsp;USA</p>"

        "<hr>"

        "<p><b>bas2tap</b><br>"
        "Copyleft &copy; 1998&#8209;2013 Martijn van der Heide, ThunderWare Research Center.<br>"
        "<br>"
        "This program is free software; you can redistribute it and/or "
        "modify it under the terms of the GNU General Public License "
        "as published by the Free Software Foundation; either version 2 "
        "of the License, or (at your option) any later version.<br>"
        "<br>"
        "This program is distributed in the hope that it will be useful, "
        "but WITHOUT ANY WARRANTY; without even the implied warranty of "
        "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the "
        "GNU General Public License for more details.<br>"
        "<br>"
        "You should have received a copy of the GNU General Public License "
        "along with this program; if not, write to the Free Software "
        "Foundation,&nbsp;Inc., 59&nbsp;Temple Place - Suite&nbsp;330, "
        "Boston, MA&nbsp;&nbsp;02111&nbsp;&#8209;&nbsp;1307,&nbsp;USA.</p>"

        "<hr>"

        "<p><b>tape2wav</b><br>"
        "Copyright &copy; 2007 Fredrick Meunier<br>"
        "Copyright &copy; 2014&#8209;2015 Sergio Baldovi<br>"
        "<br>"
        "This program is free software; you can redistribute it and/or modify "
        "it under the terms of the GNU General Public License as published by "
        "the Free Software Foundation; either version 2 of the License, or "
        "(at your option) any later version.<br>"
        "<br>"
        "This program is distributed in the hope that it will be useful, "
        "but WITHOUT ANY WARRANTY; without even the implied warranty of "
        "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the "
        "GNU General Public License for more details.<br>"
        "<br>"
        "You should have received a copy of the GNU General Public License along "
        "with this program; if not, write to the Free Software Foundation,&nbsp;Inc., "
        "51&nbsp;Franklin Street, Fifth Floor, Boston, MA&nbsp;02110&#8209;1301&nbsp;USA.</p>"

        "<hr>"

        "<p><b>LibSpectrum</b><br>"
        "Copyright &copy; 2001&#8209;2015 Philip Kendall, Darren Salt, Fredrick Meunier<br>"
        "<br>"
        "This program is free software; you can redistribute it and/or modify "
        "it under the terms of the GNU General Public License as published by "
        "the Free Software Foundation; either version 2 of the License, or "
        "(at your option) any later version.<br>"
        "<br>"
        "This program is distributed in the hope that it will be useful, "
        "but WITHOUT ANY WARRANTY; without even the implied warranty of "
        "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the "
        "GNU General Public License for more details.<br>"
        "<br>"
        "You should have received a copy of the GNU General Public License along "
        "with this program; if not, write to the Free Software Foundation,&nbsp;Inc., "
        "51&nbsp;Franklin Street, Fifth Floor, Boston, MA&nbsp;02110&#8209;1301&nbsp;USA.</p>"

        "<hr>"

        "<p><b>LZSA</b><br>"
        "Copyright &copy; 2019 Emmanuel Marty<br>"
        "<br>"
        "The LZSA code is available under the Zlib license, except for src/matchfinder.c "
        "which is placed under the Creative Commons CC0 license.<br>"
        "<br>"
        "This software is provided 'as&#8209;is', without any express or implied warranty. In "
        "no event will the authors be held liable for any damages arising from the use of "
        "this software.<br>"
        "<br>"
        "Permission is granted to anyone to use this software for any purpose, including "
        "commercial applications, and to alter itand redistribute it freely, subject to "
        "the following restrictions:<br>"
        "<ul>"
        "<li>The origin of this software must not be misrepresented; you must not claim "
        "that you wrote the original software. If you use this software in a product, "
        "an acknowledgment in the product documentation would be appreciated but is "
        "not required.<br></li>"
        "<li>Altered source versions must be plainly marked as such, and must not be "
        "misrepresented as being the original software.<br></li>"
        "<li>This notice may not be removed or altered from any source distribution.<br></li>"
        "</ul></p>"

        "<hr>"

        "<p><b>RapidXML</b><br>"
        "Copyright &copy; 2006, 2007 Marcin Kalicinski<br>"
        "<br>"
        "Permission is hereby granted, free of charge, to any person or organization "
        "obtaining a copy of the software and accompanying documentation covered by "
        "this license (the &quot;Software&quot;) to use, reproduce, display, distribute, "
        "execute, and transmit the Software, and to prepare derivative works of the "
        "Software, and to permit third-parties to whom the Software is furnished to "
        "do so, all subject to the following:<br>"
        "<br>"
        "The copyright notices in the Software and this entire statement, including "
        "the above license grant, this restriction and the following disclaimer, "
        "must be included in all copies of the Software, in whole or in part, and "
        "all derivative works of the Software, unless such copies or derivative "
        "works are solely in the form of machine-executable object code generated by "
        "a source language processor.<br>"
        "<br>"
        "THE SOFTWARE IS PROVIDED &quot;AS IS&quot;, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR "
        "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, "
        "FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT "
        "SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE "
        "FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, "
        "ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER "
        "DEALINGS IN THE SOFTWARE.</p>"

        "<hr>"

        "<p><b>ZX7</b><br>"
        "Copyright &copy; Einar Saukas<br>"
        "<br>"
        "The optimal C compressor is available under the &quot;BSD-3&quot; license.<br>"
        "<br>"
        "The Z80 assembly decompressors can be used freely within your own ZX&#8209;Spectrum "
        "programs (or any other Z80 platform), even for commercial releases. The only "
        "condition is that you must indicate somehow in your documentation that you have "
        "used &quot;ZX7&quot;.</p>"

        "</body></html>"
        ));
}

ThirdPartyDialog::~ThirdPartyDialog()
{
}
