#include "ThirdPartyDialog.h"
#include "ui_ThirdPartyDialog.h"

ThirdPartyDialog::ThirdPartyDialog(QWidget* parent)
    : QDialog(parent)
    , mUi(new Ui_ThirdPartyDialog)
{
    mUi->setupUi(this);
    mUi->textView->setHtml(QStringLiteral(
        "<html><body>"

        "<p><b>ASM</b><br>"
        "Copyright &copy; 2000-2011 INRIA, France Telecom<br>"
        "All rights reserved.<br>"
        "<br>"
        "Redistribution and use in source and binary forms, with or without "
        "modification, are permitted provided that the following conditions "
        "are met:<br>"
        "<ul>"
        "<li>Redistributions of source code must retain the above copyright "
        "notice, this list of conditions and the following disclaimer.<br></li>"
        "<li>Redistributions in binary form must reproduce the above copyright "
        "notice, this list of conditions and the following disclaimer in the "
        "documentation and/or other materials provided with the distribution.<br></li>"
        "<li>Neither the name of the copyright holders nor the names of its "
        "contributors may be used to endorse or promote products derived from "
        "this software without specific prior written permission.<br></li>"
        "</ul>"
        "<p>THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" "
        "AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE "
        "IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE "
        "ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE "
        "LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR "
        "CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF "
        "SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS "
        "INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN "
        "CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) "
        "ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF "
        "THE POSSIBILITY OF SUCH DAMAGE.</p>"

        "<hr>"

        "<p><b>AudioFile</b><br>"
        "Copyright &copy; 1998&#8209;2000, 2003&#8209;2004, 2010&#8209;2013 Michael Pruett<br>"
        "Copyright &copy; 2000&#8209;2001 Silicon Graphics, Inc.<br>"
        "<br>"
        "This library is free software; you can redistribute it and/or "
        "modify it under the terms of the GNU Lesser General Public "
        "License as published by the Free Software Foundation; either "
        "version 2.1 of the License, or (at your option) any later version.<br>"
        "<br>"
        "This library is distributed in the hope that it will be useful, "
        "but WITHOUT ANY WARRANTY; without even the implied warranty of "
        "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU "
        "Lesser General Public License for more details.<br>"
        "<br>"
        "You should have received a copy of the GNU Lesser General Public "
        "License along with this library; if not, write to the "
        "Free Software Foundation,&nbsp;Inc., 51&nbsp;Franklin Street, Fifth Floor, "
        "Boston, MA&nbsp;&nbsp;02110&nbsp;&#8209;&nbsp;1301&nbsp;&nbsp;USA</p>"

        "<hr>"

        "<p><b>bas2tap</b><br>"
        "Copyleft &copy; 1998&#8209;2013 Martijn van der Heide, ThunderWare Research Center.<br>"
        "<br>"
        "This program is free software; you can redistribute it and/or "
        "modify it under the terms of the GNU General Public License "
        "as published by the Free Software Foundation; either version 2 "
        "of the License, or (at your option) any later version.<br>"
        "<br>"
        "This program is distributed in the hope that it will be useful, "
        "but WITHOUT ANY WARRANTY; without even the implied warranty of "
        "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the "
        "GNU General Public License for more details.<br>"
        "<br>"
        "You should have received a copy of the GNU General Public License "
        "along with this program; if not, write to the Free Software "
        "Foundation,&nbsp;Inc., 59&nbsp;Temple Place - Suite&nbsp;330, "
        "Boston, MA&nbsp;&nbsp;02111&nbsp;&#8209;&nbsp;1307,&nbsp;USA.</p>"

        "<hr>"

        "<p><b>Farm-Fresh Web Icons</b><br>"
        "Copyright &copy; 2009-2014 FatCow Web Hosting. All rights reserved.<br>"
        "<br>"
        "These icon sets are licensed under a Creative Commons Attribution 3.0 License. "
        "This means you can freely use these icons for any purpose, private and commercial, "
        "including online services, templates, themes and software. However, you should "
        "include a link to this page ("
        "<a href=\"http://www.fatcow.com/free-icons\">http://www.fatcow.com/free-icons</a>"
        ") in your credits (software or website). The icons may not be resold, sub-licensed, "
        "rented, transferred or otherwise made available for use. Please link to this page "
        "on fatcow.com if you would like to spread the word.</p>"

        "<hr>"

        "<p><b>Fast and flexible Z80/i8080 emulator.</b><br>"
        "Copyright &copy; 2017 Ivan Kosarev<br>"
        "<br>"
        "Permission is hereby granted, free of charge, to any person obtaining a copy "
        "of this software and associated documentation files (the \"Software\"), to deal "
        "in the Software without restriction, including without limitation the rights "
        "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell "
        "copies of the Software, and to permit persons to whom the Software is "
        "furnished to do so, subject to the following conditions:<br>"
        "<br>"
        "The above copyright notice and this permission notice shall be included in all "
        "copies or substantial portions of the Software.<br>"
        "<br>"
        "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR "
        "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, "
        "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE "
        "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER "
        "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, "
        "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE "
        "SOFTWARE.</p>"

        "<hr>"

        "<p><b>Fugue Icons</b><br>"
        "Copyright &copy; 2013 Yusuke Kamiyamane. All rights reserved.<br>"
        "<a href=\"https://p.yusukekamiyamane.com/\">https://p.yusukekamiyamane.com/</a>.<br>"
        "<br>"
        "These icons are licensed under a Creative Commons Attribution 3.0 License.</p>"

        "<hr>"

        "<p><b>LibSpectrum</b><br>"
        "Copyright &copy; 2001&#8209;2015 Philip Kendall, Darren Salt, Fredrick Meunier<br>"
        "<br>"
        "This program is free software; you can redistribute it and/or modify "
        "it under the terms of the GNU General Public License as published by "
        "the Free Software Foundation; either version 2 of the License, or "
        "(at your option) any later version.<br>"
        "<br>"
        "This program is distributed in the hope that it will be useful, "
        "but WITHOUT ANY WARRANTY; without even the implied warranty of "
        "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the "
        "GNU General Public License for more details.<br>"
        "<br>"
        "You should have received a copy of the GNU General Public License along "
        "with this program; if not, write to the Free Software Foundation,&nbsp;Inc., "
        "51&nbsp;Franklin Street, Fifth Floor, Boston, MA&nbsp;02110&#8209;1301&nbsp;USA.</p>"

        "<hr>"

        "<p><b>LZSA</b><br>"
        "Copyright &copy; 2019 Emmanuel Marty<br>"
        "<br>"
        "The LZSA code is available under the Zlib license, except for src/matchfinder.c "
        "which is placed under the Creative Commons CC0 license.<br>"
        "<br>"
        "This software is provided 'as&#8209;is', without any express or implied warranty. In "
        "no event will the authors be held liable for any damages arising from the use of "
        "this software.<br>"
        "<br>"
        "Permission is granted to anyone to use this software for any purpose, including "
        "commercial applications, and to alter itand redistribute it freely, subject to "
        "the following restrictions:<br>"
        "<ul>"
        "<li>The origin of this software must not be misrepresented; you must not claim "
        "that you wrote the original software. If you use this software in a product, "
        "an acknowledgment in the product documentation would be appreciated but is "
        "not required.<br></li>"
        "<li>Altered source versions must be plainly marked as such, and must not be "
        "misrepresented as being the original software.<br></li>"
        "<li>This notice may not be removed or altered from any source distribution.</li>"
        "</ul>"

        "<hr>"

        "<p><b>Simple DirectMedia Layer</b><br>"
        "Copyright &copy; 1997-2020 Sam Lantinga &lt;slouken@libsdl.org&gt;<br>"
        "<br>"
        "This software is provided 'as-is', without any express or implied "
        "warranty. In no event will the authors be held liable for any damages "
        "arising from the use of this software.<br>"
        "<br>"
        "Permission is granted to anyone to use this software for any purpose, "
        "including commercial applications, and to alter it and redistribute it "
        "freely, subject to the following restrictions:<br>"
        "<ul>"
        "<li>The origin of this software must not be misrepresented; you must not "
        "claim that you wrote the original software. If you use this software "
        "in a product, an acknowledgment in the product documentation would be "
        "appreciated but is not required.<br></li>"
        "<li>Altered source versions must be plainly marked as such, and must not be "
        "misrepresented as being the original software.<br></li>"
        "<li>This notice may not be removed or altered from any source distribution.</li>"
        "</ul>"

        "<hr>"

        "<p><b>tape2wav</b><br>"
        "Copyright &copy; 2007 Fredrick Meunier<br>"
        "Copyright &copy; 2014&#8209;2015 Sergio Baldovi<br>"
        "<br>"
        "This program is free software; you can redistribute it and/or modify "
        "it under the terms of the GNU General Public License as published by "
        "the Free Software Foundation; either version 2 of the License, or "
        "(at your option) any later version.<br>"
        "<br>"
        "This program is distributed in the hope that it will be useful, "
        "but WITHOUT ANY WARRANTY; without even the implied warranty of "
        "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the "
        "GNU General Public License for more details.<br>"
        "<br>"
        "You should have received a copy of the GNU General Public License along "
        "with this program; if not, write to the Free Software Foundation,&nbsp;Inc., "
        "51&nbsp;Franklin Street, Fifth Floor, Boston, MA&nbsp;02110&#8209;1301&nbsp;USA.</p>"

        "<hr>"

        "<p><b>TinyXML</b><br>"
        "Copyright &copy; 2000-2006 Lee Thomason (www.grinninglizard.com)<br>"
        "<br>"
        "This software is provided 'as-is', without any express or implied "
        "warranty. In no event will the authors be held liable for any "
        "damages arising from the use of this software.<br>"
        "<br>"
        "Permission is granted to anyone to use this software for any "
        "purpose, including commercial applications, and to alter it and "
        "redistribute it freely, subject to the following restrictions:<br>"
        "<ul>"
        "<li>The origin of this software must not be misrepresented; you must "
        "not claim that you wrote the original software. If you use this "
        "software in a product, an acknowledgment in the product documentation "
        "would be appreciated but is not required.<br></li>"
        "<li>Altered source versions must be plainly marked as such, and "
        "must not be misrepresented as being the original software.<br></li>"
        "<li>This notice may not be removed or altered from any source "
        "distribution.</li>"
        "</ul>"

        "<hr>"

        "<p><b>ZX0</b><br>"
        "Copyright &copy; 2021, Einar Saukas<br>"
        "All rights reserved.<br>"
        "<br>"
        "Redistribution and use in source and binary forms, with or without "
        "modification, are permitted provided that the following conditions are met:<br>"
        "<ul>"
        "<li>Redistributions of source code must retain the above copyright notice, this "
        "list of conditions and the following disclaimer.<br></li>"
        "<li>Redistributions in binary form must reproduce the above copyright notice, "
        "this list of conditions and the following disclaimer in the documentation "
        "and/or other materials provided with the distribution.<br></li>"
        "<li>Neither the name of the copyright holder nor the names of its "
        "contributors may be used to endorse or promote products derived from "
        "this software without specific prior written permission.<br></li>"
        "</ul>"
        "<p>THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" "
        "AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE "
        "IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE "
        "DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE "
        "FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL "
        "DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR "
        "SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER "
        "CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, "
        "OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE "
        "OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.</p>"

        "<hr>"

        "<p><b>ZX7</b><br>"
        "Copyright &copy; Einar Saukas<br>"
        "<br>"
        "The optimal C compressor is available under the &quot;BSD-3&quot; license.<br>"
        "<br>"
        "The Z80 assembly decompressors can be used freely within your own ZX&#8209;Spectrum "
        "programs (or any other Z80 platform), even for commercial releases. The only "
        "condition is that you must indicate somehow in your documentation that you have "
        "used &quot;ZX7&quot;.</p>"

        "</body></html>"
        ));
}

ThirdPartyDialog::~ThirdPartyDialog()
{
}
